project:
  type: website
  output-dir: docs

website:
  title: "Comercio de tecnologías sanitarias en LAC"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: comercio-global.qmd
        text: Comercio global
      - href: comercio-intrarregional.qmd
        text: Comercio intrarregional
      - href: paises.qmd
        text: Países
      - href: metodologia.qmd
        text: Metodología

format:
  html:
    theme: cosmo
    toc: true
    lang: es